services:
  db:  
    image: "postgres:16" 
    environment: 
      - POSTGRES_PASSWORD=simple123
      - POSTGRES_USER=omsai
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5429:5432"

  etl:
    build: .
    depends_on:
      - db

volumes:
  db_data: